### ISSUE TITLE
Use case for downloading torrent to file vs in memory?

### ISSUE THREAD

**Issue by hbfs** [lupus78/feedtransmission#16]
Nice project. Saved a lot of time :)

Is there a use case for downloading the torrent and writing it to a file?
https://github.com/lupus78/feedtransmission/blob/aa0bc42cf8a61422c5164623fcd4ed1e5489fdbc/feedtransmission.py#L37C26-L37C26

Adding the torrent directly from the requests response has a few benefits:

```
r = requests.get(torrent_url)

# client will base64 the torrent content for you.
tc.add_torrent(r.content)
```

1. In-memory, no duplicate write to disk. transmission writes a copy of the torrent to its own folder when adding
2. eliminates and prevents third party library issues like https://github.com/lupus78/feedtransmission/issues/3
3. removes a few imports and simplifies the code

Can send a PR if it makes sense.

**Comment by lupus78** [comment]
If the `--download-with-python` arg is provided the dlTorrent() function is not called. The file is deleted after download. 
```
--download-with-python
                        If specified the torrent file will be downloaded with
                        Python's request module, and not by Transmission.
```
