### ISSUE TITLE
addeditems.txt enhancement

### ISSUE THREAD

**Issue by dsiminiuk** [lupus78/feedtransmission#2]
Hello,

I had an idea to help with cleanup. Would it be possible to put the date into the addeditems.txt file (adjusted to parse it correctly so as not to break its function), that I can create a cleanup script that will remove magnets older than X days. This way it will keep the file from growing too large and I can clean out the magnets no longer present in my RSS feed (from showrss.info) so that they won't be duplicated.

Simple format with date only (time not required) resolution would work fine.

`2016-01-06 magnet:?xt=urn:btih:65A866AE1...`

As an extra feature, you could build the automatic purge of the file for magnets older than X days into the main script too. That would be a nice to have but can be done externally too, so not a big deal.

Thanks
Danny

**Comment by dsiminiuk** [comment]
`--clear-added-items 0`
 could wipe the file
`--clear-added-items 10`
could wipe anything older than 10 days.

Just a thought on how to leverage the existing argument.

**Comment by lupus78** [comment]
Why is it a problem if addeditems.txt grows too large?

**Comment by dsiminiuk** [comment]
I have a lot of shows in my RSS feed (~30). If I delete the addeditems file, all the shows in my feed are added back to transmission again and that cleanup could be totally avoided. Having to delete it ever could be avoided if it were trimmed to exclude only those things that might be duplicated (not expired from the feed just yet). It's not a huge deal to delete (again) the torrents that I've already completed previously, but it would be a nice-to-have for housekeeping.

Is there no performance hit for having a huge file to parse and exclude every time pass? At what size (or number of elements) does it become an issue? I just don't know.

Thanks
Danny

**Comment by lupus78** [comment]
It has to be a fairly large file to hit any issues with reading and parsing. I'll do some testing, cause you made me curious.

But if you are concerned, you can write a script which deletes the X lines from the beginning of addeditems.txt. Google for solution, I think `sed` is the linux tool for that.

**Comment by dsiminiuk** [comment]
This is working

`sed -ni '1h;1!H;${;g;s/.*\n\(\(.*\n\)\{XX\}\)/\1/;p;}' addeditems.txt`

Where XX is the number of lines you want to keep from the bottom up (keep XX most recent).

**Comment by lupus78** [comment]
Cool.

Did my test.
On my laptop (i3,4gb ram), 1million lines took 0.7sec, 5million took 3.8sec
On my Raspberry PI (where I use it). 100.000 lines tooks 1.9sec, 1million took 16sec, 5 million took 1min 34 secs.

So over 100.000 lines it is getting slow, but that so large number... the added items is 7.6MB, with 1million lines is 76MB... I doubt you ever reach that size.
