### ISSUE TITLE
Support for downloadDir

### ISSUE THREAD

**Issue by martinml** [lupus78/feedtransmission#4]
`transmissionrpc` [allows specifying the download directory](https://pythonhosted.org/transmissionrpc/reference/transmissionrpc.html#transmissionrpc.Client.add_torrent) of the torrents. Maybe a new argument could be added to optionally specify a path, instead of using the default Transmission directory. It would be useful for categorizing downloads.

**Comment by lupus78** [comment]
Good point. I just saw that this has been done is some of the forks, but that code wasn't perfect.

I have just implemented it, and uploaded. Have fun using it :)
https://github.com/lupus78/feedtransmission/commit/02e04e0d6360fdce2432596f0860d7e80556392e
