### ISSUE TITLE
magnet link instead of torrents parser?

### ISSUE THREAD

**Issue by shohart** [lupus78/feedtransmission#7]
Hello, the thing is - i have a torznab rss feed generated by jackett, and only magnet links in it are usable. Is it possible to implement an option to parse torznab magnet links values?

**Comment by lupus78** [comment]
I don't know what that is, but you are free to submit a pull request.

**Comment by Tony763** [comment]
With client update, magnets works a same way as http or https if they are included in link field. If jackett produce a standard scheme then now it should work out of the box. Tested with random rss feed.

**Comment by lupus78** [comment]
Perfect, I close this issue
